# Generated by Django 4.2 on 2025-08-24 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0008_alter_game_content_alter_review_content'),
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadGameFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.URLField(unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_gamefiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
