# Generated by Django 4.2 on 2024-09-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game_category',
            field=models.ManyToManyField(related_name='user_game_category', to='games.gamecategory'),
        ),
        migrations.AlterUniqueTogether(
            name='botcnt',
            unique_together={('user', 'date')},
        ),
    ]
