# Generated by Django 4.2 on 2025-06-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_tech',
        ),
    ]
