# Generated by Django 4.2 on 2025-05-21 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import games.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBuildPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('want_roles', models.JSONField()),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='images/thumbnail/teambuildings/')),
                ('purpose', models.CharField(choices=[('PORTFOLIO', '포트폴리오'), ('CONTEST', '공모전'), ('STUDY', '스터디'), ('COMMERCIAL', '상용화')], max_length=20)),
                ('duration', models.CharField(choices=[('3M', '3개월 이내'), ('6M', '6개월 이내'), ('1Y', '1년 이내'), ('GT1Y', '1년 이상')], max_length=10)),
                ('meeting_type', models.CharField(choices=[('ONLINE', '온라인'), ('OFFLINE', '오프라인'), ('BOTH', '둘다 가능')], max_length=10)),
                ('deadline', models.DateField()),
                ('contact', models.CharField(max_length=100)),
                ('content', models.TextField(validators=[games.models.validate_text_content])),
                ('is_visible', models.BooleanField(default=True)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_build_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamBuildScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('PR', '프로필'), ('PT', '모집글')], max_length=4)),
                ('content_id', models.PositiveIntegerField()),
                ('src', models.ImageField(blank=True, null=True, upload_to='images/screenshot/teambuildings/')),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamBuildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.CharField(choices=[('STUDENT', '대학생'), ('JOBSEEKER', '취준생'), ('WORKER', '현직자')], max_length=10)),
                ('my_role', models.CharField(choices=[('NONE', '관심분야 없음'), ('ALL', 'All'), ('DIR', 'Director (PM/PO)'), ('2DG', '2D Graphic'), ('CA', 'Concept Art'), ('UXUI', 'UX/UI'), ('ART', 'Artist'), ('3DG', '3D Graphic'), ('MDL', 'Modeler'), ('FE', 'Frontend'), ('BE', 'Backend')], max_length=4)),
                ('tech_stack', models.TextField(blank=True, max_length=200, null=True)),
                ('portfolio', models.JSONField(blank=True, null=True)),
                ('purpose', models.CharField(choices=[('PORTFOLIO', '포트폴리오'), ('CONTEST', '공모전'), ('STUDY', '스터디'), ('COMMERCIAL', '상용화')], max_length=20)),
                ('duration', models.CharField(choices=[('3M', '3개월 이내'), ('6M', '6개월 이내'), ('1Y', '1년 이내'), ('GT1Y', '1년 이상')], max_length=10)),
                ('meeting_type', models.CharField(choices=[('ONLINE', '온라인'), ('OFFLINE', '오프라인'), ('BOTH', '둘다 가능')], max_length=10)),
                ('contact', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(validators=[games.models.validate_text_content])),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_build_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamBuildPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('is_visible', models.BooleanField(default=True)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='teambuildings.teambuildpost')),
            ],
        ),
    ]
