# Generated by Django 4.2 on 2025-05-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teambuildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teambuildprofile',
            name='my_role',
            field=models.CharField(choices=[('NONE', '관심분야 없음'), ('ALL', 'All'), ('DIR', 'Game Director'), ('PM', 'Project Manager'), ('PO', 'Product Owner'), ('GDES', 'Game Designer'), ('SYSD', 'System Designer'), ('LVLD', 'Level Designer'), ('CONT', 'Content Designer'), ('BAL', 'Balance Designer'), ('ECON', 'Economy Designer'), ('LOCA', 'Localization Manager'), ('ADIR', 'Art Director'), ('CART', 'Concept Artist'), ('2D', '2D Artist'), ('3D', '3D Artist'), ('MDLR', '3D Modeler'), ('RIG', 'Rigger'), ('ANIM', 'Animator'), ('TEX', 'Texture Artist'), ('LIGH', 'Lighting Artist'), ('ENV', 'Environment Artist'), ('VFX', 'VFX Artist'), ('UIUX', 'UI/UX Designer'), ('CLNT', 'Client Developer'), ('FRNT', 'Frontend Developer'), ('BACK', 'Backend Developer'), ('SRVR', 'Server Developer'), ('TOOL', 'Tools Developer'), ('NET', 'Network Programmer'), ('ENGN', 'Engine Programmer'), ('COMP', 'Composer'), ('SFX', 'Sound Designer'), ('AUDI', 'Audio Engineer'), ('QA', 'QA Tester'), ('QAPL', 'QA Planner'), ('AUTO', 'Test Automation Engineer'), ('LIVE', 'Live Ops Manager'), ('DATA', 'Data Analyst'), ('BIZ', 'Business Analyst'), ('COMM', 'Community Manager'), ('CS', 'Customer Support'), ('MKT', 'Marketing Manager'), ('MON', 'Monetization Designer'), ('VIS', 'Visual Designer')], max_length=4),
        ),
    ]
