# Generated by Django 4.2 on 2025-06-02 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import teambuildings.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0008_alter_game_content_alter_review_content'),
        ('teambuildings', '0002_alter_teambuildprofile_my_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='teambuildprofile',
            name='game_genre',
            field=models.ManyToManyField(related_name='team_build_profile', to='games.gamecategory'),
        ),
        migrations.AddField(
            model_name='teambuildprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/teambuildings/'),
        ),
        migrations.AlterField(
            model_name='teambuildpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_build_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='teambuildpost',
            name='want_roles',
        ),
        migrations.AddField(
            model_name='teambuildpost',
            name='want_roles',
            field=models.ManyToManyField(related_name='team_build_post', to='teambuildings.role'),
        ),
        migrations.AlterField(
            model_name='teambuildprofile',
            name='my_role',
            field=models.ForeignKey(on_delete=models.SET(teambuildings.models.TeamBuildProfile.if_role_deleted), related_name='team_build_profile', to='teambuildings.role'),
        ),
    ]
