# Generated by Django 4.2 on 2025-06-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teambuildings', '0003_role_teambuildprofile_game_genre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamBuildScreenshot',
        ),
    ]
