# Generated by Django 4.2 on 2025-07-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teambuildings', '0004_delete_teambuildscreenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='teambuildpost',
            name='content_text',
            field=models.TextField(blank=True, null=True, verbose_name='only text of content'),
        ),
        migrations.AddField(
            model_name='teambuildprofile',
            name='content_text',
            field=models.TextField(blank=True, null=True, verbose_name='only text of content'),
        ),
    ]
