# Generated by Django 4.2 on 2025-06-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_game_content_alter_review_content'),
        ('teambuildings', '0004_alter_teambuildprofile_game_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teambuildprofile',
            name='game_genre',
            field=models.ManyToManyField(related_name='team_build_profile', to='games.gamecategory'),
        ),
    ]
