# Generated by Django 4.2 on 2024-12-17 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0003_alter_playlog_end_at_alter_playlog_start_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deny_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deny_logs_admin', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deny_logs_game', to='games.game')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deny_logs_maker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
