# Generated by Django 4.2 on 2024-12-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_denylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalplaytime',
            name='totaltime',
            field=models.IntegerField(default=0),
        ),
    ]
