# Generated by Django 4.2 on 2025-01-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_delete_denylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='base_control',
        ),
        migrations.RemoveField(
            model_name='game',
            name='release_note',
        ),
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(upload_to='images/thumbnail/'),
        ),
    ]
