# Generated by Django 4.2 on 2025-03-19 07:14

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_remove_game_base_control_remove_game_release_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='content',
            field=models.TextField(validators=[games.models.validate_text_content]),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(max_length=300),
        ),
    ]
