# Generated by Django 4.2 on 2025-01-03 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_delete_denylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qnas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRegisterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_game', to='games.game')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_maker', to=settings.AUTH_USER_MODEL)),
                ('recoder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_recoder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
