# Generated by Django 4.2 on 2025-03-05 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qnas', '0002_gameregisterlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
