# Generated by Django 4.2 on 2025-03-05 08:31

from django.conf import settings
from django.db import migrations, models
import qnas.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qnas', '0003_deleteusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameregisterlog',
            name='maker',
            field=models.ForeignKey(on_delete=models.SET(qnas.models.set_admin_user_FK), related_name='logs_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameregisterlog',
            name='recoder',
            field=models.ForeignKey(on_delete=models.SET(qnas.models.set_admin_staff_FK), related_name='logs_recoder', to=settings.AUTH_USER_MODEL),
        ),
    ]
